server:
  port: 9006
spring:
  application:
    name: lagou-config
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/xiaoyangzhang/stage-3-module-4.git
eureka:
  client:
    service-url:
      defaultZone: http://lagou-server-A:8761/eureka,http://lagou-server-B:8762/eureka
