spring:
  application:
    name:lagou-service-code
  cloud:
    config:
      #      server:
      #        git:
      #          uri: https://github.com/xiaoyangzhang/lagou-config.git
      #          username: xiaoyangzhang1990@163.com
      #          password: zxy227575
      #          search-paths:
      #            - lagou-config
      #      label: master
      name: lagou-config
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    #    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf8&useUnicode=true
  #eureka:
  #  client:
  #    service-url:
  #      defaultZone: http://lagou-server-A:8761/eureka,http://lagou-server-B:8762/eureka
  #spring:
  #  datasource:
  #    driver-class-name: com.mysql.jdbc.Driver
  #    username: root
  #    password: root
  ##    type: com.alibaba.druid.pool.DruidDataSource
  #    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf8&useUnicode=true
  #  application:
  #    name: service-common
  profiles: dev